export const seedCategories = [
  { legacyId: '1', name: 'General', color: 'hsl(210, 70%, 50%)' },
  { legacyId: '2', name: 'Leadership', color: 'hsl(280, 70%, 50%)' },
  { legacyId: '3', name: 'Certified Training', color: 'hsl(140, 70%, 40%)' },
  { legacyId: '4', name: 'Internal Training', color: 'hsl(30, 80%, 50%)' },
];

export const seedTrainings = [
  {
    legacyId: '1',
    name: 'Project Management Fundamentals',
    description: 'Learn the essential principles of project management including planning, execution, and monitoring.',
    short_description: 'Master the basics of project management in this comprehensive workshop.',
    categoryLegacyId: '1',
    date: '2026-02-15T00:00:00.000Z',
    end_date: '2026-02-15T00:00:00.000Z',
    time_from: '09:00',
    time_to: '17:00',
    duration: '8 hours',
    status: 'Scheduled',
    available_slots: 15,
    max_registrations: 25,
    registration_method: 'internal',
    external_link: null,
    hero_image: null,
    is_featured: true,
    is_recommended: true,
    is_registration_open: true,
    display_order: 1,
    location: 'Training Room A, Building 1',
    speakers: 'John Anderson',
    target_audience: 'General',
  },
  {
    legacyId: '2',
    name: 'Leadership Excellence Program',
    description: 'Develop your leadership skills with this intensive program designed for emerging leaders.',
    short_description: 'Transform your leadership capabilities and inspire your team.',
    categoryLegacyId: '2',
    date: '2026-02-20T00:00:00.000Z',
    end_date: '2026-02-22T00:00:00.000Z',
    time_from: '09:00',
    time_to: '17:00',
    duration: '3 days',
    status: 'Scheduled',
    available_slots: 8,
    max_registrations: 20,
    registration_method: 'internal',
    external_link: null,
    hero_image: null,
    is_featured: true,
    is_recommended: true,
    is_registration_open: true,
    display_order: 2,
    location: 'Executive Conference Center',
    speakers: 'Dr. Sarah Mitchell, Michael Chen',
    target_audience: 'Senior Specialist and Above',
  },
  {
    legacyId: '3',
    name: 'AWS Cloud Certification Prep',
    description: 'Prepare for the AWS Solutions Architect certification with hands-on labs and expert guidance.',
    short_description: 'Get certified in AWS cloud technologies.',
    categoryLegacyId: '3',
    date: '2026-03-01T00:00:00.000Z',
    end_date: '2026-03-05T00:00:00.000Z',
    time_from: '09:00',
    time_to: '17:00',
    duration: '5 days',
    status: 'Scheduled',
    available_slots: 12,
    max_registrations: 15,
    registration_method: 'external',
    external_link: 'https://aws.amazon.com/training',
    hero_image: null,
    is_featured: true,
    is_recommended: false,
    is_registration_open: true,
    display_order: 3,
    location: 'Virtual / Online',
    speakers: 'AWS Certified Instructors',
    target_audience: 'Specialist and Below',
  },
  {
    legacyId: '4',
    name: 'Effective Communication Skills',
    description: 'Enhance your verbal and written communication skills for professional success.',
    short_description: null,
    categoryLegacyId: '1',
    date: '2026-01-25T00:00:00.000Z',
    end_date: '2026-01-25T00:00:00.000Z',
    time_from: '10:00',
    time_to: '15:00',
    duration: '5 hours',
    status: 'In Progress',
    available_slots: 5,
    max_registrations: 30,
    registration_method: 'internal',
    external_link: null,
    hero_image: null,
    is_featured: false,
    is_recommended: true,
    is_registration_open: true,
    display_order: null,
    location: 'Training Room B, Building 2',
    speakers: 'Emily Roberts',
    target_audience: 'General',
  },
  {
    legacyId: '5',
    name: 'Internal Compliance Training',
    description: 'Mandatory compliance training covering company policies and procedures.',
    short_description: null,
    categoryLegacyId: '4',
    date: '2026-01-20T00:00:00.000Z',
    end_date: '2026-01-20T00:00:00.000Z',
    time_from: '09:00',
    time_to: '12:00',
    duration: '3 hours',
    status: 'Completed',
    available_slots: 0,
    max_registrations: 50,
    registration_method: 'internal',
    external_link: null,
    hero_image: null,
    is_featured: false,
    is_recommended: false,
    is_registration_open: false,
    display_order: null,
    location: 'Main Auditorium',
    speakers: 'Compliance Team',
    target_audience: 'General',
  },
  {
    legacyId: '6',
    name: 'Design Thinking Workshop',
    description: 'Learn design thinking methodology to solve complex problems creatively.',
    short_description: null,
    categoryLegacyId: '1',
    date: '2026-02-28T00:00:00.000Z',
    end_date: '2026-02-28T00:00:00.000Z',
    time_from: '09:00',
    time_to: '17:00',
    duration: 'Full day',
    status: 'Scheduled',
    available_slots: 20,
    max_registrations: 25,
    registration_method: 'internal',
    external_link: null,
    hero_image: null,
    is_featured: false,
    is_recommended: true,
    is_registration_open: true,
    display_order: null,
    location: 'Innovation Lab',
    speakers: 'Alex Thompson',
    target_audience: 'Managers and Above',
  },
  {
    legacyId: '7',
    name: 'Agile Scrum Master Training',
    description: 'Become a certified Scrum Master with this comprehensive training program.',
    short_description: null,
    categoryLegacyId: '3',
    date: '2026-03-10T00:00:00.000Z',
    end_date: '2026-03-12T00:00:00.000Z',
    time_from: '09:00',
    time_to: '17:00',
    duration: '3 days',
    status: 'Scheduled',
    available_slots: 10,
    max_registrations: 15,
    registration_method: 'internal',
    external_link: null,
    hero_image: null,
    is_featured: false,
    is_recommended: false,
    is_registration_open: true,
    display_order: null,
    location: 'Training Center',
    speakers: 'Scrum Alliance Trainer',
    target_audience: 'Senior Specialist and Above',
  },
  {
    legacyId: '8',
    name: 'Team Building Essentials',
    description: 'Build stronger teams through effective collaboration and trust-building exercises.',
    short_description: null,
    categoryLegacyId: '4',
    date: '2026-03-15T00:00:00.000Z',
    end_date: '2026-03-15T00:00:00.000Z',
    time_from: '09:00',
    time_to: '16:00',
    duration: '7 hours',
    status: 'Scheduled',
    available_slots: 25,
    max_registrations: 30,
    registration_method: 'internal',
    external_link: null,
    hero_image: null,
    is_featured: false,
    is_recommended: false,
    is_registration_open: true,
    display_order: null,
    location: 'Outdoor Activity Center',
    speakers: 'HR Development Team',
    target_audience: 'Directors and Above',
  },
];

export const seedRegistrations = [
  {
    legacyId: '1',
    trainingLegacyId: '1',
    participant_name: 'John Smith',
    participant_email: 'john.smith@company.com',
    registered_at: '2026-01-15T00:00:00.000Z',
    status: 'confirmed',
    attendance_status: 'pending',
  },
  {
    legacyId: '2',
    trainingLegacyId: '1',
    participant_name: 'Jane Doe',
    participant_email: 'jane.doe@company.com',
    registered_at: '2026-01-16T00:00:00.000Z',
    status: 'registered',
    attendance_status: 'pending',
  },
  {
    legacyId: '3',
    trainingLegacyId: '2',
    participant_name: 'Mike Johnson',
    participant_email: 'mike.johnson@company.com',
    registered_at: '2026-01-17T00:00:00.000Z',
    status: 'pending_approval',
    attendance_status: 'pending',
  },
  {
    legacyId: '4',
    trainingLegacyId: '1',
    participant_name: 'Sarah Wilson',
    participant_email: 'sarah.wilson@company.com',
    registered_at: '2026-01-18T00:00:00.000Z',
    status: 'hr_approval',
    attendance_status: 'pending',
  },
  {
    legacyId: '5',
    trainingLegacyId: '5',
    participant_name: 'Tom Brown',
    participant_email: 'tom.brown@company.com',
    registered_at: '2026-01-10T00:00:00.000Z',
    status: 'confirmed',
    attendance_status: 'attended',
  },
  {
    legacyId: '6',
    trainingLegacyId: '5',
    participant_name: 'Emily Davis',
    participant_email: 'emily.davis@company.com',
    registered_at: '2026-01-11T00:00:00.000Z',
    status: 'confirmed',
    attendance_status: 'no_show',
  },
  {
    legacyId: '7',
    trainingLegacyId: '2',
    participant_name: 'Alex Turner',
    participant_email: 'alex.turner@company.com',
    registered_at: '2026-01-19T00:00:00.000Z',
    status: 'waitlisted',
    attendance_status: 'pending',
  },
  {
    legacyId: '8',
    trainingLegacyId: '3',
    participant_name: 'Lisa Chen',
    participant_email: 'lisa.chen@company.com',
    registered_at: '2026-01-20T00:00:00.000Z',
    status: 'on_hold',
    attendance_status: 'pending',
  },
];

export const seedResources = [
  {
    legacyId: '1',
    title: 'Employee Training Guidelines',
    type: 'Guideline',
    external_link: '#',
  },
  {
    legacyId: '2',
    title: 'Training Registration User Guide',
    type: 'User Guide',
    external_link: '#',
  },
  {
    legacyId: '3',
    title: 'Training Request Template',
    type: 'Template',
    external_link: '#',
  },
  {
    legacyId: '4',
    title: 'Frequently Asked Questions',
    type: 'FAQ',
    external_link: '#',
  },
];

export const seedLearningPlatforms = [
  {
    legacyId: '1',
    name: 'Blackboard',
    icon: 'GraduationCap',
    url: 'http://elearn.ku.ac.ae/',
  },
  {
    legacyId: '2',
    name: 'LinkedIn Learning',
    icon: 'Linkedin',
    url: 'https://www.linkedin.com/learning',
  },
  {
    legacyId: '3',
    name: 'Coursera',
    icon: 'BookOpen',
    url: 'https://www.coursera.org',
  },
];
